
sudo: required

language: java

services:
- docker

after_success:
- docker build -t se_methods .
- docker run se_methods

FROM openjdk:latest
COPY ./target/seMethods-0.1.0.1-jar-with-dependencies.jar /tmp
WORKDIR /tmp
ENTRYPOINT ["java", "-jar", "seMethods-0.1.0.1-jar-with-dependencies.jar"]